package com.android.summer.csula.foodvoter.polls;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.support.design.widget.TabLayout;
import android.support.v4.app.Fragment;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;
import android.view.View;
import android.widget.Button;

import com.android.summer.csula.foodvoter.R;
import com.android.summer.csula.foodvoter.models.User;
import com.android.summer.csula.foodvoter.polls.models.Poll;
import com.android.summer.csula.foodvoter.yelpApi.models.Coordinate;
import com.android.summer.csula.foodvoter.yelpApi.models.YelpPriceLevel;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.net.URL;

public class PollActivity extends AppCompatActivity implements
        SettingFragment.OnPollSettingsListener, InvitedVotersFragment.OnPollInvitesListener {

    private static final String TAG = PollActivity.class.getSimpleName();
    private static final String EXTRA_USER_ID = "userId";
    private static final String EXTRA_ONLINE = "online";
    private static final String EXTRA_USERNAME = "username";
    private static final String FIREBASE_NODE_POLLS = "polls";

    private DatabaseReference pollRef;
    private User user;
    private Poll poll;
    boolean savePoll;

    public PollActivity() {}

    public static Intent newIntent(Context context, User user) {
        Intent intent = new Intent(context, PollActivity.class);
        intent.putExtra(EXTRA_USER_ID, user.getId());
        intent.putExtra(EXTRA_ONLINE, user.isOnline());
        intent.putExtra(EXTRA_USERNAME, user.getUsername());
        return intent;
    }

    private static User getUserFromIntent(Intent intent) {
        return new User(
                intent.getStringExtra(EXTRA_USERNAME),
                intent.getStringExtra(EXTRA_USER_ID),
                intent.getBooleanExtra(EXTRA_ONLINE, true));
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_poll_configuration);

        user = getUserFromIntent(getIntent());

        initializeFirebasePollReference();

        initializeUI();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        Log.d(TAG, "onDestroy()");
        if (savePoll) {
            // User finished configuring the poll, save it permanently to Firebase and
            // indicate the it active (starting).
            writePollToFirebase();
        }
    }

    private void initializeFirebasePollReference() {
        pollRef = FirebaseDatabase.getInstance().getReference().child(FIREBASE_NODE_POLLS).push();

        // We will use the database key (its unique) generated by firebase as our poll id
        poll = new Poll(user, pollRef.getKey());
    }

    private void initializeUI() {
        initTabLayout();
        initSubmitButton();
    }

    private void initTabLayout() {
        TabLayout tabLayout = (TabLayout) findViewById(R.id.tab_layout_poll);
        tabLayout.addOnTabSelectedListener(new TabLayout.OnTabSelectedListener() {
            @Override
            public void onTabSelected(TabLayout.Tab tab) {
                swapFragment(tab);
            }

            @Override
            public void onTabUnselected(TabLayout.Tab tab) { }

            @Override
            public void onTabReselected(TabLayout.Tab tab) { }
        });


        // Use setting as the default tab, the Poll object should be mostly null values
        getSupportFragmentManager()
                .beginTransaction()
                .add(R.id.poll_fragment_container, SettingFragment.newInstance(poll))
                .commit();

    }

    private void initSubmitButton() {
        Button submit = (Button) findViewById(R.id.button_submit_poll);
        submit.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                try {
                    writePollToFirebase();
                    URL url = PollUtilities.toURL(poll);
                    Intent intent = new Intent(PollActivity.this, PollIntentService.class);
                    intent.putExtra("url", url);
                    intent.putExtra("pollId", poll.getPollId());
                    startService(intent);
                    // TODO: a push notification should appear that will lead all invited users to the voting Activities
                    finish();
                } catch (Exception e) {
                    e.printStackTrace();
                    Log.e(TAG, "Creating Yelp Search URL failed", e);
                    // Remove the poll from firebase just in cae it is
                    // written but the above operations failed
                    pollRef.setValue(null);
                }
            }
        });
    }

    private void swapFragment(TabLayout.Tab tab) {
        String selectedTab = tab.getText().toString();
        String settings = getResources().getString(R.string.tab_item_settings);
        String invites = getResources().getString(R.string.tab_item_invites);

        if (selectedTab.equals(settings)) {
            replaceFragment(SettingFragment.newInstance(poll));
        } else if (selectedTab.equals(invites)) {
            replaceFragment(InvitedVotersFragment.newInstance(poll));
        }
    }

    private void replaceFragment(Fragment fragment) {
        getSupportFragmentManager()
                .beginTransaction()
                .replace(R.id.poll_fragment_container, fragment)
                .commit();

    }

    private void writePollToFirebase() {
        pollRef.setValue(poll);
    }


    /*  These methods are used for Fragment to Activity communications */

    @Override
    public void onTitleChange(String title) {
        poll.setTitle(title);
    }

    @Override
    public void onDescriptionChange(String description) {
        poll.setDescription(description);
    }

    @Override
    public void onOpenNowChange(boolean openNow) {
        poll.setOpenNow(openNow);
    }

    @Override
    public void onPriceChange(String price) {
        // Price would be in Yelp's price level format ($, $$, $$$, $$$$) but the API
        // uses integer (1,2,3,4) instead. We convert it to an intge String, a value that Yelp
        // api requires
        poll.setPrice(YelpPriceLevel.fromYelpString(price));
    }

    @Override
    public void onZipCodeChange(String zipCode) {
        // We either use zip code as our location to OR the geolocation to make an API call to Yelp,
        // so we set one of to null to know which one to use
        poll.setCoordinate(null);
        poll.setZipCode(zipCode);
    }

    @Override
    public void onCoordinateChange(Coordinate coordinate) {
        // We either use zip code as our location to OR the geolocation to make an API call to Yelp,
        // so we set one of to null to know which one to use
        poll.setZipCode(null);
        poll.setCoordinate(coordinate);
    }

    @Override
    public void onUserInvited(String userId) {
        poll.addVoters(userId);
    }

    @Override
    public void onUserUninvited(String userId) {
        poll.removeVoters(userId);
    }
}
